FORMAT: 1A


# Index [/]

## Root [GET]

Test getting the application root.

## Alternative method [POST]

Test sending a request with alternative method

# Static routes [/resources]

## Get a static resource [GET]

Test fetching a static resource

# Parameterized routes [/resources/{id}]

## Get a parameterized resource [GET]

Test fetching a static resource
